[workspace]
members = ["kernel", "application", "driver", "server"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
nitinol = { git = "https://github.com/HalsekiRaika/nitinol", rev = "8c634351d099910b27d26622201ced3914896fc9", features = ["eventsource"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time", "net", "signal"] }
bytes = "1"
async-trait = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
kernel = { package = "shuttlepub-kernel", path = "kernel" }
application = { package = "shuttlepub-application", path = "application" }
driver = { package = "shuttlepub-driver", path = "driver" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"

[profile.release]
lto = "thin"
strip = true
